appr:
- name: quay.io/samsung_cnct/fluent-bit
  repository: appr://
  version: 0.0.5-0
- name: quay.io/samsung_cnct/elasticsearch-chart
  repository: appr://
  version: 0.0.3-0
- name: quay.io/samsung_cnct/curator
  repository: appr://
  version: 0.0.4-0
- name: quay.io/samsung_cnct/kibana-chart
  repository: appr://
  version: 0.1.3-0
- name: quay.io/samsung_cnct/eventrouter
  repository: appr://
  version: 0.0.3-0
